global:
  resolve_timeout: 5m

route:
  receiver: local-dev-null
  group_by:
    - alertname
    - severity
    - component
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: local-dev-null

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal:
      - alertname
      - component
