CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'repl_password';

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE orders REPLICA IDENTITY FULL;

DROP PUBLICATION IF EXISTS orders_pub;
CREATE PUBLICATION orders_pub FOR TABLE orders;