global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: clickhouse
    static_configs:
      - targets: ["clickhouse:9363"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: flink
    static_configs:
      - targets:
          - "flink-jobmanager:9249"
          - "flink-taskmanager:9249"

  - job_name: cdc-validation
    static_configs:
      - targets: ["cdc-validation-exporter:9108"]
